import type { Level, Question } from "./questions";

const phrasalVerb = (
  id: string,
  sentence: string,
  answers: string[],
  level: Level,
  hint: string,
): Question => ({ id, sentence, answers, level, hint });

const musicPhrasalVerb = (
  id: string,
  sentence: string,
  answers: string[],
  level: Level,
  hint: string,
  artist: string,
  song: string,
): Question => ({
  id,
  sentence,
  answers,
  level,
  hint,
  source: { artist, song },
});

export const PHRASAL_VERB_QUESTIONS: Question[] = [
  phrasalVerb("pv-a1-1", "I ___ at seven every morning.", ["wake up"], "A1", "stop sleeping"),
  phrasalVerb("pv-a1-2", "Please ___; breakfast is ready.", ["get up"], "A1", "leave your bed"),
  phrasalVerb("pv-a1-3", "Please ___ and make yourself comfortable.", ["sit down"], "A1", "take a seat"),
  phrasalVerb("pv-a1-4", "Everyone must ___ when the teacher enters.", ["stand up"], "A1", "rise to your feet"),
  phrasalVerb("pv-a1-5", "The door is open, so please ___!", ["come in"], "A1", "enter"),
  phrasalVerb("pv-a1-6", "We usually ___ on Friday evenings.", ["go out"], "A1", "leave home for fun"),
  phrasalVerb("pv-a1-7", "Could you ___ the kitchen light?", ["turn on", "switch on"], "A1", "start a device"),
  phrasalVerb("pv-a1-8", "Please ___ the television before bed.", ["turn off", "switch off"], "A1", "stop a device"),
  phrasalVerb("pv-a1-9", "You should ___ a coat; it is cold outside.", ["put on"], "A1", "dress in"),
  phrasalVerb("pv-a1-10", "Please ___ your shoes at the door.", ["take off"], "A1", "remove clothing"),
  phrasalVerb("pv-a1-11", "I need to ___ my keys before we leave.", ["look for"], "A1", "try to find"),
  phrasalVerb("pv-a1-12", "Can you ___ that parcel from the floor?", ["pick up"], "A1", "lift"),
  phrasalVerb("pv-a1-13", "___, or we will miss the bus!", ["hurry up"], "A1", "move faster"),
  phrasalVerb("pv-a1-14", "What time will you ___ from work?", ["come back", "get back"], "A1", "return here"),
  phrasalVerb("pv-a1-15", "I forgot my wallet, so I have to ___ home.", ["go back"], "A1", "return there"),
  phrasalVerb("pv-a1-16", "Please ___ my phone number.", ["write down", "note down"], "A1", "record in writing"),
  phrasalVerb("pv-a1-17", "We need to ___ the kitchen after dinner.", ["clean up", "tidy up"], "A1", "make tidy"),
  phrasalVerb("pv-a1-18", "I am busy now, but I will ___ later.", ["call back", "phone back"], "A1", "telephone again"),
  phrasalVerb("pv-a1-19", "Can I ___ this shirt before buying it?", ["try on"], "A1", "test some clothing"),
  phrasalVerb("pv-a1-20", "Please ___; you are walking too fast.", ["slow down"], "A1", "reduce speed"),
  musicPhrasalVerb("pv-a1-music-1", "Please ___ before the alarm rings again.", ["wake up"], "A1", "stop sleeping", "Avicii", "Wake Me Up"),
  musicPhrasalVerb("pv-a1-music-2", "Remember to ___ the laptop before bed.", ["shut down", "switch off", "turn off"], "A1", "stop a device", "BLACKPINK", "Shut Down"),
  musicPhrasalVerb("pv-a1-music-3", "We should ___ home before it gets dark.", ["get back", "go back"], "A1", "return", "The Beatles", "Get Back"),
  musicPhrasalVerb("pv-a1-music-4", "Let's ___ some music while we cook.", ["put on"], "A1", "start playing", "Corinne Bailey Rae", "Put Your Records On"),
  musicPhrasalVerb("pv-a1-music-5", "Please ___; I cannot walk that quickly.", ["slow down"], "A1", "reduce speed", "Selena Gomez", "Slow Down"),
  musicPhrasalVerb("pv-a1-music-6", "It was only a small mistake, so try to ___ .", ["shake it off"], "A1", "stop worrying about it", "Taylor Swift", "Shake It Off"),

  phrasalVerb("pv-a2-1", "Could you ___ my cat while I am away?", ["look after", "take care of"], "A2", "care for"),
  phrasalVerb("pv-a2-2", "We need to ___ the bus near the library.", ["get on"], "A2", "enter public transport"),
  phrasalVerb("pv-a2-3", "Remember to ___ at the final stop.", ["get off"], "A2", "leave public transport"),
  phrasalVerb("pv-a2-4", "We have ___ milk, so I will buy some.", ["run out of"], "A2", "have none left"),
  phrasalVerb("pv-a2-5", "Please ___ the book when you finish it.", ["give back"], "A2", "return something"),
  phrasalVerb("pv-a2-6", "I need to ___ these shoes because they are too small.", ["take back"], "A2", "return to a shop"),
  phrasalVerb("pv-a2-7", "Do not ___ that box; we can reuse it.", ["throw away", "throw out"], "A2", "put in the rubbish"),
  phrasalVerb("pv-a2-8", "Please ___ this form before your appointment.", ["fill in", "fill out"], "A2", "complete a form"),
  phrasalVerb("pv-a2-9", "We should ___ online before going to the airport.", ["check in"], "A2", "register for a journey"),
  phrasalVerb("pv-a2-10", "Guests must ___ before eleven in the morning.", ["check out"], "A2", "leave a hotel"),
  phrasalVerb("pv-a2-11", "She wants to be a doctor when she ___ .", ["grows up"], "A2", "becomes an adult"),
  phrasalVerb("pv-a2-12", "We often ___ at the park after class.", ["hang out"], "A2", "spend time together"),
  phrasalVerb("pv-a2-13", "Let us ___ tonight instead of cooking.", ["eat out", "dine out"], "A2", "eat at a restaurant"),
  phrasalVerb("pv-a2-14", "I ___ at the gym three times a week.", ["work out"], "A2", "exercise"),
  phrasalVerb("pv-a2-15", "You can ___ the word in an online dictionary.", ["look up"], "A2", "search for information"),
  phrasalVerb("pv-a2-16", "Can you help me ___ my new computer?", ["set up"], "A2", "prepare for use"),
  phrasalVerb("pv-a2-17", "He did not ___ for the meeting yesterday.", ["show up", "turn up"], "A2", "arrive"),
  phrasalVerb("pv-a2-18", "Please ___ with your story; I am listening.", ["carry on", "go on"], "A2", "continue"),
  phrasalVerb("pv-a2-19", "Take a breath and try to ___ .", ["calm down"], "A2", "become relaxed"),
  phrasalVerb("pv-a2-20", "I need to ___ what time the shop closes.", ["find out"], "A2", "discover information"),
  musicPhrasalVerb("pv-a2-music-1", "She wants to travel more when she ___ .", ["grows up"], "A2", "becomes an adult", "Paramore", "Grow Up"),
  musicPhrasalVerb("pv-a2-music-2", "Could you ___ my plants while I am away?", ["look after", "take care of"], "A2", "care for", "The Fray", "Look After You"),
  musicPhrasalVerb("pv-a2-music-3", "Even when the task feels difficult, we must ___ .", ["carry on", "go on"], "A2", "continue", "fun.", "Carry On"),
  musicPhrasalVerb("pv-a2-music-4", "You should ___ that new café this weekend.", ["check out"], "A2", "visit or investigate", "will.i.am & Nicki Minaj", "Check It Out"),
  musicPhrasalVerb("pv-a2-music-5", "They decided to ___ after another argument.", ["break up", "split up"], "A2", "end a relationship", "Dua Lipa", "Break My Heart"),
  musicPhrasalVerb("pv-a2-music-6", "Why don't you ___ after work?", ["come over", "come round"], "A2", "visit my home", "Rudimental feat. Anne-Marie and Tion Wayne", "Come Over"),

  phrasalVerb("pv-b1-1", "Please do not ___ that old argument again.", ["bring up"], "B1", "mention a topic"),
  phrasalVerb("pv-b1-2", "They had to ___ the picnic because of the rain.", ["call off"], "B1", "cancel"),
  phrasalVerb("pv-b1-3", "We cannot ___ the decision any longer.", ["put off"], "B1", "delay"),
  phrasalVerb("pv-b1-4", "She knows how to ___ difficult customers.", ["deal with"], "B1", "manage a situation"),
  phrasalVerb("pv-b1-5", "I ___ my new neighbours very well.", ["get on with", "get along with"], "B1", "have a good relationship"),
  phrasalVerb("pv-b1-6", "Old machines sometimes ___ without warning.", ["break down"], "B1", "stop working"),
  phrasalVerb("pv-b1-7", "We need to ___ why the payment failed.", ["figure out", "work out"], "B1", "understand or solve"),
  phrasalVerb("pv-b1-8", "Do not ___ just because the task is difficult.", ["give up"], "B1", "stop trying"),
  phrasalVerb("pv-b1-9", "She decided to ___ photography as a hobby.", ["take up"], "B1", "start an activity"),
  phrasalVerb("pv-b1-10", "He had to ___ the job offer because of the salary.", ["turn down"], "B1", "refuse"),
  phrasalVerb("pv-b1-11", "I should ___ one small mistake in the report.", ["point out"], "B1", "draw attention to"),
  phrasalVerb("pv-b1-12", "We need to ___ this problem before Friday.", ["sort out"], "B1", "solve"),
  phrasalVerb("pv-b1-13", "I ___ an old photograph while cleaning the attic.", ["came across", "ran across"], "B1", "found by chance"),
  phrasalVerb("pv-b1-14", "It took her months to ___ the disappointment.", ["get over"], "B1", "recover emotionally"),
  phrasalVerb("pv-b1-15", "I ___ seeing you again next weekend.", ["look forward to"], "B1", "feel excited about"),
  phrasalVerb("pv-b1-16", "Let us meet for coffee and ___ each other.", ["catch up with"], "B1", "exchange recent news"),
  phrasalVerb("pv-b1-17", "It is difficult to ___ all the new technology.", ["keep up with"], "B1", "stay at the same pace"),
  phrasalVerb("pv-b1-18", "He tried to ___ an excuse for being late.", ["make up"], "B1", "invent"),
  phrasalVerb("pv-b1-19", "I promised to help, and I do not want to ___ her.", ["let down"], "B1", "disappoint"),
  phrasalVerb("pv-b1-20", "A new manager will ___ the team next month.", ["take over"], "B1", "assume control"),
  musicPhrasalVerb("pv-b1-music-1", "Even after two failed attempts, she refused to ___ .", ["give up"], "B1", "stop trying", "Linkin Park", "Given Up"),
  musicPhrasalVerb("pv-b1-music-2", "We need to ___ how this machine works.", ["figure out", "work out"], "B1", "understand", "Royal Blood", "Figure It Out"),
  musicPhrasalVerb("pv-b1-music-3", "Try not to ___ with regret; focus on today.", ["look back"], "B1", "think about the past", "Oasis", "Don't Look Back in Anger"),
  musicPhrasalVerb("pv-b1-music-4", "I am relying on you, so please do not ___ .", ["let me down"], "B1", "disappoint me", "The Chainsmokers", "Don't Let Me Down"),
  musicPhrasalVerb("pv-b1-music-5", "The file was corrupted, so I had to ___ .", ["start over", "start again"], "B1", "begin again", "Miley Cyrus", "Start All Over"),
  musicPhrasalVerb("pv-b1-music-6", "Take a breath and ___ before the interview.", ["calm down"], "B1", "become relaxed", "Rema", "Calm Down"),

  phrasalVerb("pv-b2-1", "The new policy could ___ major changes in the workplace.", ["bring about"], "B2", "cause to happen"),
  phrasalVerb("pv-b2-2", "We need to ___ a more creative solution.", ["come up with"], "B2", "produce an idea"),
  phrasalVerb("pv-b2-3", "I am trying to ___ the amount of coffee I drink.", ["cut down on"], "B2", "consume less"),
  phrasalVerb("pv-b2-4", "The company wants to ___ unnecessary paperwork.", ["do away with"], "B2", "abolish"),
  phrasalVerb("pv-b2-5", "The agreement may ___ if nobody compromises.", ["fall through"], "B2", "fail to happen"),
  phrasalVerb("pv-b2-6", "I finally ___ organising the photographs.", ["got around to"], "B2", "eventually found time"),
  phrasalVerb("pv-b2-7", "She had to ___ several interviews before getting the job.", ["go through"], "B2", "experience a process"),
  phrasalVerb("pv-b2-8", "The restaurant did not ___ its excellent reviews.", ["live up to"], "B2", "meet expectations"),
  phrasalVerb("pv-b2-9", "I will not ___ that noise every night.", ["put up with"], "B2", "tolerate"),
  phrasalVerb("pv-b2-10", "The doctor could not ___ a food allergy.", ["rule out"], "B2", "eliminate a possibility"),
  phrasalVerb("pv-b2-11", "Try to ___ some money for unexpected expenses.", ["set aside", "put aside"], "B2", "reserve"),
  phrasalVerb("pv-b2-12", "It is important to ___ people who are treated unfairly.", ["stand up for", "stick up for"], "B2", "defend"),
  phrasalVerb("pv-b2-13", "She agreed to ___ more responsibility at work.", ["take on"], "B2", "accept responsibility"),
  phrasalVerb("pv-b2-14", "The simple repair ___ to be quite expensive.", ["turned out"], "B2", "eventually proved"),
  phrasalVerb("pv-b2-15", "The receipts will ___ your expense claim.", ["back up"], "B2", "provide evidence"),
  phrasalVerb("pv-b2-16", "I need to ___ my Spanish before the trip.", ["brush up on"], "B2", "improve an old skill"),
  phrasalVerb("pv-b2-17", "The shop plans to ___ single-use plastic bags.", ["phase out"], "B2", "gradually stop using"),
  phrasalVerb("pv-b2-18", "The team managed to ___ the difficult event successfully.", ["pull off"], "B2", "achieve something difficult"),
  phrasalVerb("pv-b2-19", "The director decided to ___ after ten years.", ["step down"], "B2", "leave a senior role"),
  phrasalVerb("pv-b2-20", "The council promised to ___ illegal dumping.", ["crack down on"], "B2", "take strict action against"),
  musicPhrasalVerb("pv-b2-music-1", "She agreed to ___ more responsibility at work.", ["take on"], "B2", "accept responsibility", "a-ha", "Take On Me"),
  musicPhrasalVerb("pv-b2-music-2", "He decided to ___ the offer because the hours were unsuitable.", ["turn down"], "B2", "refuse", "DJ Snake & Lil Jon", "Turn Down for What"),
  musicPhrasalVerb("pv-b2-music-3", "Please ___ him; it is his first day.", ["go easy on"], "B2", "treat less severely", "Adele", "Easy on Me"),
  musicPhrasalVerb("pv-b2-music-4", "I am trying to ___ late-night snacks.", ["cut down on"], "B2", "consume less", "Ed Sheeran", "Bad Habits"),
  musicPhrasalVerb("pv-b2-music-5", "The sequel struggled to ___ everyone's expectations.", ["live up to"], "B2", "meet expectations", "Imagine Dragons", "Whatever It Takes"),
  musicPhrasalVerb("pv-b2-music-6", "The dancers managed to ___ a difficult routine live.", ["pull off"], "B2", "achieve something difficult", "Beyoncé", "Run the World (Girls)"),

  phrasalVerb("pv-c1-1", "The disagreement seems to ___ a lack of trust.", ["boil down to"], "C1", "have as the essential cause"),
  phrasalVerb("pv-c1-2", "The small bakery hopes to ___ catering next year.", ["branch out into"], "C1", "expand into a new area"),
  phrasalVerb("pv-c1-3", "We need to ___ the detailed work this afternoon.", ["buckle down to"], "C1", "start working seriously"),
  phrasalVerb("pv-c1-4", "She ___ her success to consistent practice.", ["chalked up"], "C1", "attributed"),
  phrasalVerb("pv-c1-5", "The regulator intends to ___ misleading advertising.", ["clamp down on"], "C1", "control more strictly"),
  phrasalVerb("pv-c1-6", "The proposal has ___ strong criticism from residents.", ["come in for"], "C1", "received criticism"),
  phrasalVerb("pv-c1-7", "The company must ___ the consequences of its decision.", ["face up to"], "C1", "accept a difficult reality"),
  phrasalVerb("pv-c1-8", "Could you ___ the final section with more examples?", ["flesh out"], "C1", "add more detail"),
  phrasalVerb("pv-c1-9", "The report should not ___ the risks involved.", ["gloss over"], "C1", "avoid discussing properly"),
  phrasalVerb("pv-c1-10", "Both sides met to ___ the remaining details.", ["iron out"], "C1", "resolve small difficulties"),
  phrasalVerb("pv-c1-11", "I will ___ you: the project is behind schedule.", ["level with"], "C1", "speak honestly"),
  phrasalVerb("pv-c1-12", "We have ___ the candidates to a final three.", ["narrowed down"], "C1", "reduce the number of options"),
  phrasalVerb("pv-c1-13", "We will have to wait and see how the plan ___ .", ["pans out"], "C1", "develops in the end"),
  phrasalVerb("pv-c1-14", "The spokesperson tried to ___ the seriousness of the error.", ["play down"], "C1", "make seem less important"),
  phrasalVerb("pv-c1-15", "The audit aims to ___ waste throughout the organisation.", ["root out"], "C1", "find and remove completely"),
  phrasalVerb("pv-c1-16", "It would be unfair to ___ one employee for blame.", ["single out"], "C1", "select one person"),
  phrasalVerb("pv-c1-17", "The contract must ___ exactly what each side will provide.", ["spell out"], "C1", "explain explicitly"),
  phrasalVerb("pv-c1-18", "She finally decided to ___ the problem directly.", ["square up to"], "C1", "face a difficult situation"),
  phrasalVerb("pv-c1-19", "We should ___ the advantages and disadvantages first.", ["weigh up"], "C1", "consider carefully"),
  phrasalVerb("pv-c1-20", "The discussion began to ___ the real cause of the delay.", ["zero in on"], "C1", "focus precisely on"),
  musicPhrasalVerb("pv-c1-music-1", "The disagreement really ___ a lack of trust.", ["boils down to"], "C1", "has as its essential cause", "Queen", "Under Pressure"),
  musicPhrasalVerb("pv-c1-music-2", "The interview helped to ___ the reasoning behind her decision.", ["flesh out"], "C1", "add more detail to", "Billie Eilish", "Therefore I Am"),
  musicPhrasalVerb("pv-c1-music-3", "The inquiry was created to ___ corruption in the industry.", ["root out"], "C1", "find and remove completely", "Florence + the Machine", "Shake It Out"),
  musicPhrasalVerb("pv-c1-music-4", "The documentary ___ the role of social pressure.", ["zeroes in on", "zeros in on"], "C1", "focuses precisely on", "Hozier", "Take Me to Church"),
  musicPhrasalVerb("pv-c1-music-5", "The article unfairly ___ one player for blame.", ["singled out"], "C1", "selected one person", "ABBA", "The Winner Takes It All"),
  musicPhrasalVerb("pv-c1-music-6", "The guide ___ exactly what visitors should expect.", ["spells out"], "C1", "explains explicitly", "Harry Styles", "Sign of the Times"),
];
